version: "3.8"
services:
  mysql_user:
    image: mysql:8.0
    container_name: mysql-container1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: likedin
      MYSQL_USER: sakib
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    expose:
      - "3307"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=caching_sha2_password
    networks:
      - internalnet

  mysql_post:
    image: mysql:8.0
    container_name: mysql-post-container1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: likedin
      MYSQL_USER: sakib
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - "3308"
    volumes:
      - ./init_post.sql:/docker-entrypoint-initdb.d/init_post.sql
    command: --default-authentication-plugin=caching_sha2_password
    networks:
      - internalnet

  postobj:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9050:9050"
    environment:
      MINIO_ROOT_USER: 44Ede1q8sa8uRHXBZ52K
      MINIO_ROOT_PASSWORD: 8H5S84ijB5wRES2YgTRELVowwNj4mLk8ZiYV2kkr
    command: server --address 0.0.0.0:9000 /data
    volumes:
      - minio-data:/data

  user_server:
    image: user_service
    # depends_on:
    #   - mysql_user
    # healthcheck:
    #   test: ["CMD", "mysql", "-h", "mysql", "-u", "sakib", "-p", "password", "-e", "SELECT 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    build: ./user-service
    restart: unless-stopped
    networks:
      - internalnet
    ports:
      - "3005:3005"
    expose:
      - "3005"
    command: ["./wait-for-mysql.sh", "mysql-container1:3307", "npm", "start"]
    

  post_server:
    image: post_service
    # depends_on:
    #   - mysql_post
    # healthcheck:
    #   test: ["CMD", "mysql", "-h", "mysql", "-u", "sakib", "-p", "password", "-e", "SELECT 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    build: ./Post_service
    restart: unless-stopped
    networks:
      - internalnet
    ports:
      - "3006:3006"
    expose:
      - "3006"
    command: ["./wait-for-mysql.sh", "mysql-post-container1:3308", "npm", "start"]

networks:
  internalnet:
    driver: bridge

volumes:
  minio-data:
