version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container1
    # environment:
    #   MYSQL_ROOT_PASSWORD: password # Change this to your desired root password
    #   MYSQL_DATABASE: likedin # Change this to your desired database name
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # ports:
    #   - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: likedin
      MYSQL_USER: sakib
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3307
    ports:
    - 3307:3307
    expose:
      - 3307
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - internalnet

  server:
    image: user_service
    build: .
    restart: unless-stopped
    networks:
      - internalnet
    ports:
    - "3005:3005"
    depends_on:
      - mysql

  # browser:
  #   image: likedin
  #   build: .
  #   restart: unless-stopped
  #   networks:
  #     - internalnet

networks:
  internalnet:
    driver: bridge
